services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - horus-network

  horus-api:
    build: .
    image: horus-api
    container_name: horus-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
      USERNAME_MAIL: ${USERNAME_MAIL}
      PASSWORD_MAIL: ${PASSWORD_MAIL}
    networks:
      - horus-network

networks:
  horus-network:
    driver: bridge

volumes:
  postgres-data: