version: '3.9'

services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - horus-network
    profiles:
      - mysql

  horus-api:
    build: ./horus-api
    container_name: horus-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AUTH_SECRET: ${AUTH_SECRET}
      USERNAME_MAIL: ${USERNAME_MAIL}
      PASSWORD_MAIL: ${PASSWORD_MAIL}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - horus-network

networks:
  horus-network:
    driver: bridge

volumes:
  mysql-data:
